### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by raihan79c** [PTNUSASATUINTIARTHA-DOKU/jokul-woocommerce-plugin#19]
![Screenshot_2021-11-16-13-44-03-68](https://user-images.githubusercontent.com/94430289/141927956-c06b4d96-9182-4781-90e7-350c76641c29.jpg)

**Comment by dokudevex** [comment]
Halo @raihan79c , Jokul Plugin hanya support ke Plugin WooCommerce bukan untuk Wordpress. Wordpress sendiri adalah generic CMS untuk blogging, news, dll. Dan itu bisa dipakai untuk Ecommerce dengan menginstall Plugin WooCommerce. Mohon dipastikan bahwa Jokul Plugin di aplikasikan ke WooCommerce. 

Terimakasih. 
- jessica

**Comment by raihan79c** [comment]
Gimana maksudnya kak "hanya support untuk Plugin Woocommerce bukan untuk Wordpress", bukannya Woocommerce itu plugin di CMS WordPress. Itu saya sudah install sesuai instruksi (diinstall di Wordpress Admin Panel>Plugin>Plugin baru), mohon bantuannya

**Comment by dokudevex** [comment]
Boleh info versi WooCommerce yg digunakan @raihan79c ?
#jessica

**Comment by raihan79c** [comment]
Versi 5.9.0

**Comment by raihan79c** [comment]
> Boleh info versi WooCommerce yg digunakan @raihan79c ? #jessica

Versi 5.9.0

**Comment by dokudevex** [comment]
halo Pak @raihan79c terimakasih laporan issue nya, saat ini sudah di update ke 1.3.2. 
bisa di coba dengan versi 1.3.2 pak

**Comment by raihan79c** [comment]
Terima kasih, sdh aktif & bisa dikonfigurasi. Apakah ada email khusus jokul yg bisa saya hubungi jika ada masalah teknis

**Comment by raihan79c** [comment]
halo

**Comment by dokudevex** [comment]
Halo @raihan79c , Apabila Bapak Raihan memerlukan informasi lainnya, silakan mengirimkan email ke care@doku.com (layanan 24 jam). Terimakasih.
