### ISSUE TITLE
Payment Channel "Jokul Chekout" error

### ISSUE THREAD

**Issue by raihan79c** [PTNUSASATUINTIARTHA-DOKU/jokul-woocommerce-plugin#20]
Maaf fungsi payment channel yg jokul checkout apa ya? Dan saya coba error gak bisa dipake. Untuk metode yg lain sdh bisa, tq
![IMG_20211118_213538](https://user-images.githubusercontent.com/94430289/142425294-389941a7-ba35-4cdb-b2cb-a123674b4891.jpg)

**Comment by dokudevex** [comment]
Hi @raihan79c , boleh diinformasikan Client ID nya, dan boleh share file doku_log, agar mempermudah tracing issuenya.

**Comment by raihan79c** [comment]
MCH-1794-1635434091303
Doku log http://zenflix.net/doku_log/log_17-Nov-2021.log

**Comment by dokudevex** [comment]
haki pak @raihan79c , 
dari log mendapat kan response : 
`{\"message\":[\"price must must be greater than 0.0\",\"country must be 2 character of country ID based on ISO COUNTRY CODES ALPHA-2\"]}`

request yang di kirim price nya 0 dan tidak ada country 

`{"order":{"invoice_number":"147","line_items":[{"name":"Diamond Mobile Legends","price":"0","quantity":1}],"amount":"45000","callback_url":"https:\/\/zenflix.net\/checkout\/order-received\/147\/?key=wc_order_vSgY2DCl2Cbp7&147","currency":"IDR"},"payment":{"payment_due_date":"1440"},"customer":{"id":null,"name":"Eko","email":"email.nackgowa@gmail.com","phone":"082190822965","country":"","address":""},"additional_info":{"integration":{"name":"woocommerce-plugin","version":"1.3.2"}}}`

**Comment by raihan79c** [comment]
Untuk country memang di formulir checkout tdk ada input country, tapi untuk error price pada saat checkout pasti ada price yg tampil kak. Apa ngebug ya tdk terbaca oleh plugin jokul nya?

**Comment by raihan79c** [comment]
close
